// @ts-check
// Sidebar auto-generated from docs/ folder structure (uses _category_.json + sidebar_position).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
